<a href="https://colab.research.google.com/github/111Vidya/Python_fundamentals/blob/main/Mar_15_Support_Vector_Machine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# SVM Classification
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.svm import SVC # Support Vector Machine
from sklearn.model_selection import GridSearchCV # GridSearchCV to experiment with Range
from sklearn.metrics import classification_report


from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score



In [ ]:
# Read file names , add coloumn names and define X and Y
filename = '/content/pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = pd.read_csv(filename, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]

In [ ]:
#split into test and training data . Add random state =42 to ensure same output all the time
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.3,random_state=42)

In [ ]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((537, 8), (537,), (231, 8), (231,))

### Grid Search CV

In [ ]:
#Initiate SVClassifier , use grid search cv . Inside grid search CV use RBF.
#Gamma values are assumptions and so are the cost values that it can experiment with and identify the best
clf = SVC()
param_grid = [{'kernel':['rbf'],'gamma':[50,5,10,0.5],'C':[15,14,13,12,11,10,0.1,0.001] }]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [15, 14, 13, 12, 11, 10, 0.1, 0.001],
                          'gamma': [50, 5, 10, 0.5], 'kernel': ['rbf']}])

In [ ]:
#Best Gamma value 50 and best Cost value 15. Accuracy at 65% not a good model
gsv.best_params_ , gsv.best_score_

({'C': 15, 'gamma': 50, 'kernel': 'rbf'}, 0.6499301187980433)

In [ ]:
#Accuracy on testing data. not a good model even on the testing data 65%
clf = SVC(C= 15, gamma = 50)
clf.fit(X_train , y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 65.36796536796537


array([[151,   0],
       [ 80,   0]])

In [ ]:
#Change the Kernel from RBF to Linear . accuracy improved to 74.45%
clf = SVC(kernel= "linear")
clf.fit(X_train , y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 74.45887445887446


array([[122,  29],
       [ 30,  50]])

In [ ]:
#Change the Kernel to Polynomial . accuracy dropped to 74.89%
clf = SVC(kernel= "poly")
clf.fit(X_train , y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 74.89177489177489


array([[133,  18],
       [ 40,  40]])

In [ ]:
#Sigmoid kernel is giving us lesser accuracy of 53.67%
clf = SVC(kernel= "sigmoid")
clf.fit(X_train , y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 53.67965367965368


array([[108,  43],
       [ 64,  16]])

Polynomial is better model with best accuracy value